###
POST http://localhost:8080/api/v1/referees
Content-Type: application/json

{
  "firstName": "Кирилл",
  "secondName": "Васько",
  "patronymic": "Андреевич",
  "category": "FIRST"
}

###
POST http://localhost:8080/api/v1/referees
Content-Type: application/json

{
  "firstName": "Максим",
  "secondName": "Маханько",
  "patronymic": "Витальевич",
  "category": "SECOND"
}

###
POST http://localhost:8080/api/v1/auth/sign-in
Content-Type: application/json

{
  "login": "Makhanko.MV",
  "password": "!T3n(G3lho"
}

###
POST http://localhost:8080/api/v1/competitions/initial
Content-Type: application/json

{
  "name": "Гродненские региональные соревнования",
  "beginDate": "2024-05-14",
  "endDate": "2024-05-24",
  "place": "Гродно, ул. Белые Росы 57, кв 7",
  "numberOfStages": 2
}

###
POST http://localhost:8080/api/v1/competitions/1/stage
Content-Type: application/json

{
  "mainCollegium": [
    {
      "refereeId": 1,
      "workPerformed": "Очень важная"
    }
  ],
  "collegium": [
    {
      "refereeId": 2,
      "workPerformed": "Не очень важная"
    }
  ],
  "stageNumber": 1
}

###
POST http://localhost:8080/api/v1/competitions/1/stage
Content-Type: application/json

{
  "mainCollegium": [
    {
      "refereeId": 1,
      "workPerformed": "Очень важная"
    },
    {
      "refereeId": 2,
      "workPerformed": "Очень важная"
    }
  ],
  "collegium": [
    {
      "refereeId": 2,
      "workPerformed": "Не очень важная"
    }
  ],
  "stageNumber": 2
}

###
GET http://localhost:8080/api/v1/referees/competitionStage/1
Content-Type: application/x-www-form-urlencoded

###
GET http://localhost:8080/api/v1/referees/competitionStage/2
Content-Type: application/x-www-form-urlencoded

###
POST http://localhost:8080/api/v1/skydivers
Content-Type: application/json

{
  "firstName": "Вера",
  "secondName": "Маханько",
  "patronymic": "Андреевна",
  "gender": "MALE",
  "birthDate": "2003-06-02",
  "placeOfBirth": "город Берёзовка",
  "placeOfWork": "ООО Модсен",
  "education": "Среднее",
  "phone": "+375259373579",
  "passportDetails": {
    "series": "KH",
    "number": "1234567",
    "personalNumber": "12345678910121",
    "issuingAuthority": "Лидский РОВД Гродненской области",
    "issuedDate": "2013-12-11"
  }
}

###
GET http://localhost:8080/api/v1/skydivers/page?number=1&size=15

###
POST http://localhost:8080/api/v1/auth/regen/1
Content-Type: application/x-www-form-urlencoded

###
GET http://localhost:8080/api/v1/referees/page?
    number=1&
    size=15&
    category=FIRST

<> 2024-05-19T193009.200.json

###
GET http://localhost:8080/api/v1/competitions?
    number=1&
    size=5&
    isCompleted=false

###
POST http://localhost:8080/api/v1/teams/competition/1
Content-Type: application/json

{
  "name": "Команда Парней",
  "members": [
    {
      "memberNumber": 1,
      "skydiverId": 3
    },
    {
      "memberNumber": 2,
      "skydiverId": 4
    }
  ]
}

###
PUT http://localhost:8080/api/v1/teams/1/competition/1
Content-Type: application/json

{
  "name": "Команда Парней",
  "members": [
    {
      "memberNumber": 1,
      "skydiverId": 3
    },
    {
      "memberNumber": 2,
      "skydiverId": 4
    }
  ]
}

###
GET http://localhost:8080/api/v1/competitions/1

###
DELETE http://localhost:8080/api/v1/individuals/5/competition/1

###
POST http://localhost:8080/api/v1/individuals/competition/1
Content-Type: application/json

{
  "skydiverId": 5,
  "memberNumber": 3
}

###
PUT http://localhost:8080/api/v1/teams/1/competition/1/exchange
Content-Type: application/json

{
  "teamMemberId": 4,
  "individualId": 5
}

###
POST http://localhost:8080/api/v1/trick-refereeing/attempts
Content-Type: application/json

{
  "trickSerieId": 1,
  "trickAttempts": {
    "TURN_1": {
      "arrowPenalty": 40,
      "dPenalty" : 40,
      "minusPenalty" : 40
    },
    "TURN_2" : {
      "dPenalty" : 40,
      "minusPenalty" : 40
    },
    "BACK_LOOP_1" : {
      "dPenalty" : 40,
      "plusMinusPenalty" : 0
    }
  }
}

###
GET http://localhost:8080/api/v1/jumping/competition/1/skydiver/4

###
POST http://localhost:8080/api/v1/jumping/competition/1
Content-Type: application/json

{
  "accuracy": 8,
  "memberNumber": 2,
  "jumpingNumber": 2,
  "performanceDate": "2024-06-02"
}

###
GET http://localhost:8080/api/v1/jumping/competition/1/skydiver/4/list

###
PUT http://localhost:8080/api/v1/jumping/competition/1/skydiver/4
Content-Type: application/json

{
  "id": 2,
  "number": 1,
  "accuracy": 7,
  "performanceDate": "2024-06-01"
}

###
DELETE http://localhost:8080/api/v1/jumping/2/competition/1