version: "3.4"

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "skydiving"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

  skydivers-back:
    image: abandonedscope/skydiving-back:latest
    container_name: skydivers-back
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/skydiving"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
      SPRING_LIQUIBASE_CONTEXTS: "dev"
    ports:
      - "8080:8080"