spring:
  application:
    name: "skydiving-competitions"
  datasource:
    url: jdbc:postgresql://localhost:5432/skydiving
    password: postgres
    username: postgres
  liquibase:
    change-log: "db/changes/db.changelog-master.xml"
    contexts: "prod"

jumping:
  limit-per-member: 10

jwt:
  secret: eWFnc2hqa2tvZHVpZnVsYXNpamtsZjthJ2Rib2ppaCBoYmtqYXNubGQ7bWtmZw==
  ttl: 1m
  issuer: "skydiving"

competition:
  update-competition-status-cron: "0 0 0 * * ?"

logging:
  level:
    org.springframework.jdbc.core: TRACE
